version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: user-lorem-ipsum-app
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    command: php -S 0.0.0.0:8000 -t /app
